name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Create the build folder
      run: |
        mkdir utf8-utf16-converter/build
        cd utf8-utf16-converter/build
    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
    - name: Test
      run: ctest
